site_name: Experimaestro (Python)
site_description: experimaestro Computer science experiments manager and scheduler

nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Concepts: concepts.md
  - Experiments:
      - Configuration: experiments/config.md
      - Plan: experiments/plan.md
  - Launchers: launchers/index.md
  - Connectors: connectors/index.md
  - CLI: cli.md
  - FAQ: faq.md

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: "green"
    accent: "green"
  font:
    text: "Roboto"
    code: "Roboto Mono"

markdown_extensions:
  # https://pypi.org/project/markdown-include
  - markdown_include.include:
      base_path: .
  - codehilite:
      linenums: false
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .

repo_url: "https://github.com/experimaestro/experimaestro-python"
