version: 2

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing packages
          command: |
            apt-get update
            apt-get install -y libpoco-dev git g++ cmake libssh-dev ninja-build doxygen python3-dev pkg-config python3-venv
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive

      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install wheel
            

      - run:
          name: Build and test
          command: |
            . venv/bin/activate
            python setup.py test
            python setup.py sdist
            python setup.py bdist_wheel

      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    docker:
      - image: "debian:buster"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            python setup.py verify
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            pip install twine
            twine upload dist/*
