version: 2

workflows:
  version: 2
  main:
    jobs:
      - build-37:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/

      - publish:
          requires:
            - build-37
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/
jobs:
  build-37:
    environment: 
      PYTHONBIN: /opt/python/cp37-cp37m/bin
    docker:
      - image: "bpiwowar/experimaestro-python"
    steps:
      - checkout
            
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive

      - run:
          name: Install requirements
          command: |
            PATH=${PYTHONBIN}:$PATH
            pip install wheel
            pip install -r requirements.txt


      - run:
          name: Build
          command: |
            PATH=${PYTHONBIN}:$PATH
            python setup.py build

      - run:
          name: Test
          command: |
            PATH=${PYTHONBIN}:$PATH
            python setup.py test

      - run:
          name: Build packages
          command: |
            PATH=$PYTHONBIN:$PATH
            python setup.py sdist
            python setup.py bdist_wheel

      # Allows twine uploads
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    docker:
      - image: "bpiwowar/experimaestro-python"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            python setup.py verify
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            pip install twine
            twine upload dist/*
