version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing packages
          command: |
            apt-get update
            apt-get install -y libpoco-dev git g++ cmake libssh-dev ninja-build doxygen python3-dev pkg-config
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update

      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install cffi click wheel twine
            python setup.py verify
            
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
        name: Build and test
        command: |
          python setup.py test
          python setup.py sdist
          python setup.py bdist_wheel

      - run:
        name: upload to pypi
        command: |
          . venv/bin/activate
          twine upload dist/*
      - run:
          name: Creating Build Files
          command: |
            cmake -GNinja -H. -Bbuild
      - run:
          name: Building
          command: |
            ninja -j 2 -C build experimaestro-tests
      - run:
          name: Test
          # TODO: run SSH server to test remote calls
          command: |
            GTEST_FILTER="-SshTest.*" CTEST_OUTPUT_ON_FAILURE=1 ninja -C build test