version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context: PyPI
          filters:
              tags:
                only: /.*/

jobs:
  build:
    docker:
      - image:  quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout

      # TODO: restore dependency cache
      # - restore_cache:
      #     key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      # - run:
      #     name: install python dependencies
      #     command: |
      #       python3 -m venv venv
      #       . venv/bin/activate
      #       make dev
      # - save_cache:
      #     key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      #     paths:
      #       - "venv"

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - run: 
          name: Upload
          command: |
            if [ "$CIRCLE_TAG" ]; then
              echo "Uploading using twine"
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
              . venv/bin/activate
              python setup.py verify
              make package
              twine upload dist/*
            fi
